name: Deploy to IIS Server

on:
  push:
    branches:
      - main  # Deploy only on main branch push

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to IIS server
        shell: pwsh
        run: |
          $password = ConvertTo-SecureString "${{ secrets.WIN_PASSWORD }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ("${{ secrets.WIN_USERNAME }}", $password)
          Invoke-Command -ComputerName "${{ secrets.WIN_SERVER }}" -Credential $credential -ScriptBlock {
              $sourcePath = "${{ github.workspace }}"  # GitHub workspace folder
              $destinationPath = "C:\inetpub\wwwroot\myapp"
              
              # Copy files to IIS folder
              Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
          }

      - name: Restart IIS
        shell: pwsh
        run: |
          $password = ConvertTo-SecureString "${{ secrets.WIN_PASSWORD }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ("${{ secrets.WIN_USERNAME }}", $password)
          Invoke-Command -ComputerName "${{ secrets.WIN_SERVER }}" -Credential $credential -ScriptBlock {
              iisreset
          }
